### Embeddings from Raw Text

POST http://localhost:7071/api/GenerateEmbeddings
Content-Type: application/json

{"TextBody": "John is not born yet."}

### Ingestion from Raw Text

POST http://localhost:7071/api/IngestText
Content-Type: application/json

{"Title": "Sample Text", 
"TextBody": "Hello."}

### Ingestion from Raw Text

POST http://localhost:7071/api/IngestText
Content-Type: application/json

{"Title": "Sample Text", 
"TextBody": "John is not born yet."}

### Send a RAG Prompt
POST http://localhost:7071/api/RAGPrompting
Content-Type: application/json

{"Prompt":"How old is John?"}